export const Songlists=[

   
    {
        id:"34",
        movie_name:"mussanjemaatu",
        song_name:"ninna nodalentho",
        singer:"",
        image_src:require("../assets/songs_images/ninna_nodalentho.jpeg"),
        song_src:require("../assets/audio_tracks/ninna_nodalentho.mp3")
    },
    {
        id:"6",
        movie_name:"mussanjemaatu",
        song_name:"yenagali",
        singer:"sudeep",
        image_src:require("../assets/songs_images/Yenagali.jpg"),
        song_src:require("../assets/audio_tracks/Yenagali.mp3")
    },
    {
        id:"35",
        movie_name:"album moon chand",
        song_name:"yeh raatein yeh mausam",
        singer:"sanam simran sehgal",
        image_src:require("../assets/songs_images/yeh_raaten_yeh_mausam.jpeg"),
        song_src:require("../assets/audio_tracks/yeh_raaten_yeh_mausam.mp3")
    },
    
    {
        id:"31",
        movie_name:"gaalipata",
        song_name:"akasha este yakedyu",
        singer:"",
        image_src:require("../assets/songs_images/akasha_este_yakedyu.jpeg") ,
        song_src: require("../assets/audio_tracks/akasha_este_yakedyu.mp3"),
    },
    {
        id:"32",
        movie_name:"jolly days",
        song_name:"raktha sambandhagala",
        singer:"",
        image_src:require("../assets/songs_images/raktha_sambandhagala.jpeg") ,
        song_src: require("../assets/audio_tracks/raktha_sambandhagala.mp3"),
    },
    {
        id:"33",
        movie_name:"jolly days",
        song_name:"jolly days",
        singer:"",
        image_src:require("../assets/songs_images/jolly_days.jpeg") ,
        song_src: require("../assets/audio_tracks/jolly_days.mp3"),
    },
    {
        id:"14",
        movie_name:"",
        song_name:"shape of you",
        singer:" ed sheeran",
        image_src:require("../assets/songs_images/Shape_of_you.jpg") ,
        song_src: require("../assets/audio_tracks/Shape_of_You.mp3"),
    },
    {
        id:"15",
        movie_name:"",
        song_name:"despacito",
        singer:"luis fonsi daddy yankee erika ender marty james andrés torres",
        image_src:require("../assets/songs_images/Despacito.jpg") ,
        song_src: require("../assets/audio_tracks/Despacito.mp3"),
    },
    {
        id:"1",
        movie_name:"googly",
        song_name:"bisilu kudure",
        singer:"",
        image_src:require('../assets/songs_images/Bisilu_kudureyondu.jpg'),
        song_src:require("../assets/audio_tracks/Bisilu_Kudure.mp3")
    },
    {
        id:"20",
        movie_name:"album",
        song_name:"desperado",
        singer:"raghav",
        image_src:require("../assets/songs_images/desperado.jpg") ,
        song_src: require("../assets/audio_tracks/desperado.mp3"),
    },
    {
        id:"2",
        movie_name:"googly",
        song_name:"yeno yeno aagide",
        singer:"",
        image_src:require("../assets/songs_images/Yeno_yeno_agide.jpg"),
        song_src:require("../assets/audio_tracks/Yeno_Yeno_Aagide.mp3")
    },
    {
        id:"3",
        movie_name:"mungarumale 2",
        song_name:"gamanisu",
        singer:"",
        image_src:require("../assets/songs_images/Gamanisu.jpg"),
        song_src:require("../assets/audio_tracks/Gamanisu.mp3")
   },
    {
        id:"4",
        movie_name:"mungarumale 2",
        song_name:"sariyaagi",
        singer:"",
        image_src:require("../assets/songs_images/Sariyaage.jpg"),
        song_src:require("../assets/audio_tracks/Sariyaagi.mp3")
    },

    {
        id:"5",
        movie_name:"4th the people",
        song_name:"lajjavathiye",
        singer:"",
        image_src:require("../assets/songs_images/Lejjavathiye.jpg"),
        song_src:require("../assets/audio_tracks/Lajjavathiyea.mp3")
    },

    {
        id:"7",
        movie_name:"adhipursh",
        song_name:"ram siya ram",
        singer:"",
        image_src:require("../assets/songs_images/Ram_siya_ram.jpg"),
        song_src:require("../assets/audio_tracks/Ram_Siya_Ram.mp3")
    },
    {
        id:"8",
        movie_name:"kantara",
        song_name:"singara siriye",
        singer:"",
        image_src:require("../assets/songs_images/singara_siriye.jpg") ,
        song_src: require("../assets/audio_tracks/Singara_Siriye.mp3"),
    },
    {
        id:"9",
        movie_name:"kantara",
        song_name:"varaha roopam",
        singer:"",
        image_src: require("../assets/songs_images/varaha_roopam.jpg"),
        song_src:require("../assets/audio_tracks/Varaha_Roopam.mp3") ,
    },
    {
        id:"10",
        movie_name:"kirik party",
        song_name:"katheyonda helide",
        singer:"",
        image_src:require("../assets/songs_images/katheyonda.jpg") ,
        song_src: require("../assets/audio_tracks/Katheyonda_Helide.mp3"),
    }
    ,
    {
        id:"11",
        movie_name:"kirik party",
        song_name:"katheyonda helide farewell",
        singer:"",
        image_src:require("../assets/songs_images/Katheyondu_farewell.jpg") ,
        song_src:require("../assets/audio_tracks/Katheyondu_Helide_Farewell.mp3") ,
    }
    ,
    {
        id:"12",
        movie_name:"kirik party",
        song_name:"thirboki jeevana",
        singer:"",
        image_src: require("../assets/songs_images/thirboki_jeevana.jpg"),
        song_src:require("../assets/audio_tracks/Thirboki_Jeevana.mp3") ,
    }
    ,
    {
        id:"13",
        movie_name:"kirik party",
        song_name:"hey who are you",
        singer:"",
        image_src:require("../assets/songs_images/Hey_who_are_you.jpg") ,
        song_src:require("../assets/audio_tracks/Hey_Who_Are_You.mp3") ,
    },
    {
        id:"16",
        movie_name:"kirik party",
        song_name:"belageddu",
        singer:"",
        image_src:require("../assets/songs_images/belageddu.jpg") ,
        song_src:require("../assets/audio_tracks/Belageddu.mp3") ,
    },
    {
        id:"17",
        movie_name:"kirik party",
        song_name:"kaagadada doniyalli",
        singer:"",
        image_src:require("../assets/songs_images/Kaggadaga_doniyalli.jpg") ,
        song_src:require("../assets/audio_tracks/Kaagadada_Doniyalli.mp3") ,
    },
    {
        id:"18",
        movie_name:"kirik party",
        song_name:"last bench party",
        singer:"",
        image_src:require("../assets/songs_images/Last_bench_party.jpg") ,
        song_src:require("../assets/audio_tracks/Last_Benchu_Party.mp3") ,
    },
    {
        id:"19",
        movie_name:"googly",
        song_name:"neenirade",
        singer:"",
        image_src:require("../assets/songs_images/Neenirade.jpg") ,
        song_src:require("../assets/audio_tracks/Neenirade.mp3") ,
    },
    {
        id:"21",
        movie_name:"ae dil hai mushkil",
        song_name:"ae dil hai mushkil",
        singer:"arjith singh",
        image_src:require("../assets/songs_images/ae_dil_hai_mushkil.jpg") ,
        song_src:require("../assets/audio_tracks/ae_dil_hai_mushkil.mp3") ,
    },
    {
        id:"22",
        movie_name:"bhediya",
        song_name:"apna bana le",
        singer:"arjith singh",
        image_src:require("../assets/songs_images/apna_bana_le.jpg") ,
        song_src:require("../assets/audio_tracks/apna_bana_le.mp3") ,
    },
    {
        id:"23",
        movie_name:"vikrant rona",
        song_name:"chikki bombe",
        singer:"vijay prakash harshitha karthik",
        image_src:require("../assets/songs_images/chikki_bombe.jpg") ,
        song_src:require("../assets/audio_tracks/chikki_bombe.mp3") ,
    },
    {
        id:"24",
        movie_name:"jailer",
        song_name:"kaavaalaa",
        singer:"shilpa rao anirudh ravichander",
        image_src:require("../assets/songs_images/kaavaalaa.jpg") ,
        song_src:require("../assets/audio_tracks/kaavaalaa.mp3") ,
    },
    {
        id:"25",
        movie_name:"coke studio album",
        song_name:"pasoori",
        singer:"shae gill ali sethi",
        image_src:require("../assets/songs_images/pasoori.jpg") ,
        song_src:require("../assets/audio_tracks/pasoori.mp3") ,
    },
   
    {
        id:"27",
        movie_name:"zara hatke zara bachke",
        song_name:"tere vaaste",
        singer:"",
        image_src:require("../assets/songs_images/tere_vaaste.jpg") ,
        song_src:require("../assets/audio_tracks/tere_vaaste.mp3") ,
    },
    {
        id:"26",
        movie_name:"vikrant rona",
        song_name:"ra ra rakkamma",
        singer:"",
        image_src:require("../assets/songs_images/ra_ra_rakkamma.jpg") ,
        song_src:require("../assets/audio_tracks/ra_ra_rakkamma.mp3") ,
    },
    {
        id:"28",
        movie_name:"ginny georgia",
        song_name:"until i found you",
        singer:"stephen sanchez em beihold",
        image_src:require("../assets/songs_images/until_i_found_you.jpg") ,
        song_src:require("../assets/audio_tracks/until_i_found_you.mp3") ,
    },
    {
        id:"29",
        movie_name:"vaa vaathi",
        song_name:"vaa vaathi",
        singer:"",
        image_src:require("../assets/songs_images/vaa_vaathi.jpg") ,
        song_src:require("../assets/audio_tracks/vaa_vaathi.mp3") ,
    },
    {
        id:"30",
        movie_name:"3 three",
        song_name:"why this kolaveri di",
        singer:"dhanush anirudh",
        image_src:require("../assets/songs_images/why_this_kolaveri_di.jpg") ,
        song_src:require("../assets/audio_tracks/why_this_kolaveri_di.mp3") ,
    },
    
    {
        id:"36",
        movie_name:"jolly days",
        song_name:"joy joy jolly",
        singer:"dhanush anirudh",
        image_src:require("../assets/songs_images/joy_joy_jolly.jpeg") ,
        song_src:require("../assets/audio_tracks/joy_joy_jolly.mp3") ,
    },
    
    
  ];